// Constants and configuration data for the Transform application
// This file contains all static configuration, tool definitions, and constants
// used throughout the application.

/**
 * Supported data format conversion types
 */
export const formats = [
    'JSON',
    'Go Struct',
    'YAML',
    'TOML',
    'XML',
    'JSON Schema',
    'GraphQL Schema',
    'Protobuf',
    'TOON',
    'MsgPack',
];

/**
 * Image formats supported for conversion
 */
export const imageFormats = ['jpg', 'png', 'webp', 'avif'];

/**
 * Human-readable labels for image formats
 */
export const imageFormatLabels = {
    jpg: 'JPG',
    png: 'PNG',
    webp: 'WebP',
    avif: 'AVIF',
};

/**
 * Format-specific options for image conversion
 */
export const imageFormatOptions = {
    jpg: [{ key: 'quality', type: 'range', min: 1, max: 100, label: 'Quality', defaultValue: 85 }],
    png: [
        {
            key: 'compression',
            type: 'range',
            min: 0,
            max: 9,
            label: 'Compression',
            hint: '0 = store, 9 = maximum',
            defaultValue: 6,
        },
    ],
    // WebP keeps a pure-Rust path; quality uses RGB quantization before lossless encode.
    webp: [
        {
            key: 'quality',
            type: 'range',
            min: 1,
            max: 100,
            label: 'Quality',
            hint: '100 = lossless (default)',
            defaultValue: 100,
        },
        {
            type: 'note',
            text: 'Lower values quantize colors before encoding so no libwebp bindings are needed.',
        },
    ],
    avif: [
        { key: 'quality', type: 'range', min: 1, max: 100, label: 'Quality', defaultValue: 80 },
        { key: 'speed', type: 'range', min: 1, max: 10, label: 'Speed (1=best)', defaultValue: 4 },
        {
            key: 'lossless',
            type: 'checkbox',
            label: 'Force lossless (quality=100)',
            defaultValue: false,
        },
    ],
};

/**
 * Sample data for each format type to demonstrate conversions
 */
export const samples = {
    JSON: '{\n  "name": "Ricky",\n  "age": 27\n}',
    XML: `<root>\n  <name>Ricky</name>\n  <age>27</age>\n</root>`,
    'Go Struct': 'type AutoGenerated struct {\n  UserID string `json:"user_id"`\n}\n',
    YAML: 'name: Ricky\nage: 27',
    TOML: 'name = "Ricky"\nage = 27',
    'JSON Schema': `{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "age": { "type": "number" }
  },
  "required": ["name"]
}`,
    'GraphQL Schema': `type AutoGenerated {
  userID: String!
}`,
    Protobuf: `message AutoGenerated {
  string user_id = 1;
}`,
    TOON: `users[2]{id,name}:
  1,Alice
  2,Bob`,
    MsgPack: 'Paste base64 MsgPack here...',
};

/**
 * Sample PEM certificate chain used for SSL inspector demos and tests
 */
export const sampleCertificateChain = `-----BEGIN CERTIFICATE-----
MIIDtDCCApygAwIBAgIJAKXzsY4GAceGMA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNV
BAYTAlVTMRcwFQYDVQQKDA5UcmFuc2Zvcm0gVGVzdDEaMBgGA1UEAwwRVHJhbnNm
b3JtIFJvb3QgQ0EwHhcNMjUxMTI2MDcxMDUwWhcNMjgwMjI5MDcxMDUwWjA/MQsw
CQYDVQQGEwJVUzEXMBUGA1UECgwOVHJhbnNmb3JtIFRlc3QxFzAVBgNVBAMMDnRy
YW5zZm9ybS50ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArjn9
UsyxJJxoH/EwemSWnb2bQEpvURklKM5P5+wmzEWALvwiwViquTCq6hjhiEU5Cfb6
bME1cgWBmsCEGK4S33IzbTdqUupaupNf2YFr0a7mRoXZtDIFGfb/3W4xg8Sp5lDd
fRvr/5QGtZCAhXoABwjI8pF5A3TGWVh37xZNrofmx1o2cbS31Vg9cTZ+YXT/72Xf
hkQBjom9SxRdO3Bub36TTdcStV8Bl9H4FNvRE9WUpY8L5qvpJETI3yJw/SD/qH7n
GGRrQYA8vQEroNaqWQGGpcurxlhsRgAew5w9UlxP5BrVUdBt5781IWfjKHlFPJD8
u4/x3mkP5jfDVQvPPwIDAQABo4GvMIGsMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgWg
MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAzBgNVHREELDAqgg50cmFu
c2Zvcm0udGVzdIISd3d3LnRyYW5zZm9ybS50ZXN0hwQKAAABMB8GA1UdIwQYMBaA
FLJcA4w4HHt9Hko8hEHCeRmhpjOAMB0GA1UdDgQWBBTLTRYdFR4zUPFcxs3dlaiE
umhy1zANBgkqhkiG9w0BAQsFAAOCAQEAruMCZG4bgXDz1BXCaMWztRoJzUvRyen9
ug4atu5Rz03WT1jVfCvp4dcupEMQYWrW1OIXF3IdpaXOOKzm44/EDu95G/mlTIST
88ao8+nDqGqM/ZPmeU1FjFF83FhrwOFOpwpWXJ+fwbzJ2ZPfG2x4BduR3l8Ykhrm
m/qhC4+gjwVBpayuTJLwnqd/7g5Vw4y+bJn87SP8qO051C/2TQWSDXEAt7YetOE8
XnNTHBPJLu6zcQ35a+aMa2GhYM02WfJUT7pgyER49Jzws0PwQT6kX9OOydabcGaK
3VQQjdHISXmkytGzcoquq0K0xjyZeadc7mzZT3n2IIg3V8HoB+Egow==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDRjCCAi6gAwIBAgIJAMiPjBY38LqXMA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNV
BAYTAlVTMRcwFQYDVQQKDA5UcmFuc2Zvcm0gVGVzdDEaMBgGA1UEAwwRVHJhbnNm
b3JtIFJvb3QgQ0EwHhcNMjUxMTI2MDcwOTU0WhcNMzUxMTI0MDcwOTU0WjBCMQsw
CQYDVQQGEwJVUzEXMBUGA1UECgwOVHJhbnNmb3JtIFRlc3QxGjAYBgNVBAMMEVRy
YW5zZm9ybSBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
8+de/n9QrCXYpuJLQ5A4NBcxu08d7N8uWfzDX3v4gsDG39EVknas4XI47fd2HN7+
k7ZZjg5t0KfQqVFmve/NImypSrlpok58NeSS2xcd/dQMX+31kTOqkoZcIsB9zrC9
0meZoJeKUdm1XTRXBb2j8KTDK6pP2PQySjf0MKEBNzw0vWhxO+nOmmy+TooHm+b4
qm5LsI27+uRx6u8iX26vwj4VoOcSMJvZM96RqImP0BfjHDT9lAqn4Flmg+TrR6Pk
h+2YHZcfHPnSAj+YAgxtFObsi0XpQZQapRiAmBQ7wovac4Yg/5Q1SSrRrUrvhR+F
M8Ux5PUJG/vce6LBgtrXLQIDAQABoz8wPTAPBgNVHRMECDAGAQH/AgEBMAsGA1Ud
DwQEAwIBhjAdBgNVHQ4EFgQUslwDjDgce30eSjyEQcJ5GaGmM4AwDQYJKoZIhvcN
AQELBQADggEBAB7DNWMSBAqNUZng2ALnC762ldv9oVljcnZwtPQOwbsLbbo4bNVr
Nyk1jOUY0PbIFtrMsbyCC4cOGBNYw1jHwKDTTyAMKEOaC/TjMMPz0kfZUTef79CD
KDpRTfzl2hJ+mRFkvJWVE6c7aSL9KGwynucW3SH6jFoIBFOUN9dsXO/XD+SRrByz
MWcQDTVseSO0jCgWsQwJSI/je4rJ9AZXmdw/wYq3yuklUAYGKkwNP8mpilYe5W5l
pe5Q2Xh4BdECbU15Txl0bzQ5QcIghAEUnGrvaFwFu1vVmsJeuRxE3MdFLW3d4d/u
F9EJGaYGzbulnbQjpZQQjsje552DD4+qsXI=
-----END CERTIFICATE-----`;

/**
 * Set of supported data formats for quick lookups
 */
export const supportedFormats = new Set(formats);

/**
 * Unit conversion keys for data size conversions
 */
export const unitKeys = [
    'bit',
    'byte',
    'kilobit',
    'kilobyte',
    'megabit',
    'megabyte',
    'gigabit',
    'gigabyte',
    'terabit',
    'terabyte',
];

/**
 * Timestamp field configurations for various formats
 */
export const timestampFields = [
    { key: 'iso8601', id: 'timestampIso' },
    { key: 'rfc3339', id: 'timestampRfc3339' },
    { key: 'rfc2822', id: 'timestampRfc' },
    { key: 'iso9075', id: 'timestampIso9075' },
    { key: 'rfc7231', id: 'timestampRfc7231' },
    { key: 'sql_datetime', id: 'timestampSql' },
    { key: 'sql_date', id: 'timestampSqlDate' },
    { key: 'timestamp_seconds', id: 'timestampSeconds' },
    { key: 'timestamp_milliseconds', id: 'timestampMillis' },
    { key: 'timestamp_microseconds', id: 'timestampMicros' },
    { key: 'timestamp_nanoseconds', id: 'timestampNanos' },
    // Browser timezone fields (readonly)
    { key: 'browser_iso8601', id: 'browserIso8601', readonly: true },
    { key: 'browser_rfc3339', id: 'browserRfc3339', readonly: true },
    { key: 'browser_rfc2822', id: 'browserRfc2822', readonly: true },
    { key: 'browser_iso9075', id: 'browserIso9075', readonly: true },
    { key: 'browser_rfc7231', id: 'browserRfc7231', readonly: true },
    { key: 'browser_sql_datetime', id: 'browserSqlDatetime', readonly: true },
    { key: 'browser_sql_date', id: 'browserSqlDate', readonly: true },
];

/**
 * Character sets for random string generation
 */
export const digitCharacters = '0123456789';
export const specialCharacters = [
    '!',
    '@',
    '#',
    '$',
    '%',
    '^',
    '&',
    '*',
    '-',
    '_',
    '+',
    '=',
    '~',
    '?',
    '/',
    '\\',
    '|',
    '[',
    ']',
    '(',
    ')',
    '{',
    '}',
    "'",
    '"',
    '.',
    ',',
    ':',
    ';',
    '`',
];

/**
 * Configuration for minimum count controls in random string generation
 */
export const minCountConfig = {
    digits: {
        stateKey: 'randomMinDigits',
        elementKey: 'randomMinDigits',
        rowKey: 'randomMinDigitsRow',
    },
    lower: {
        stateKey: 'randomMinLower',
        elementKey: 'randomMinLower',
        rowKey: 'randomMinLowerRow',
    },
    upper: {
        stateKey: 'randomMinUpper',
        elementKey: 'randomMinUpper',
        rowKey: 'randomMinUpperRow',
    },
    symbols: {
        stateKey: 'randomMinSymbols',
        elementKey: 'randomMinSymbols',
    },
};

/**
 * Coder tool definitions for encoding/decoding operations
 */
export const coderTools = [
    {
        id: 'coder-encode',
        mode: 'encode',
        label: 'Base Encoders',
        description: 'Base32/64/85/91 encodings.',
    },
    {
        id: 'coder-decode',
        mode: 'decode',
        label: 'Base Decoders',
        description: 'Decode BaseX back to plain text.',
    },
    {
        id: 'coder-hash',
        mode: 'hash',
        label: 'Hash',
        description: 'Hashes from stdlib.',
    },
    {
        id: 'coder-url',
        pair: 'url',
        label: 'URL Encode/Decode',
        description: 'Bidirectional URL percent-encoding helper.',
    },
    {
        id: 'coder-jwt',
        pair: 'jwt',
        label: 'JWT Encode/Decode',
        description: 'Sign JSON payloads and inspect JWT tokens.',
    },
    {
        id: 'coder-kdf',
        mode: 'kdf',
        label: 'Password Hashers',
        description: 'Bcrypt / Argon2 generate and verify.',
    },
    {
        id: 'security-crypto',
        label: 'Encrypt / Decrypt',
        description: 'AES-GCM + (X)ChaCha20 for text/files.',
    },
    {
        id: 'security-ssl',
        label: 'SSL Inspector',
        description: 'Parse PEM certificates or full chains.',
    },
];

/**
 * Maps coder tool IDs to their operating modes
 */
export const coderToolModes = {
    'coder-encode': 'encode',
    'coder-decode': 'decode',
    'coder-hash': 'hash',
};

/**
 * Encoding groups and their variants for base encoding operations
 */
export const encodingGroups = [
    {
        id: 'base16',
        label: 'Base16',
        variants: [{ key: 'hex_upper', label: 'Hex' }],
    },
    {
        id: 'base32',
        label: 'Base32',
        variants: [
            { key: 'base32_standard', label: 'Standard' },
            { key: 'base32_standard_no_padding', label: 'Standard(no padding)' },
            { key: 'base32_hex', label: 'Hex' },
            { key: 'base32_hex_no_padding', label: 'Hex(no padding)' },
        ],
    },
    {
        id: 'base64',
        label: 'Base64',
        variants: [
            { key: 'base64_standard', label: 'Standard' },
            { key: 'base64_raw_standard', label: 'Standard(no padding)' },
            { key: 'base64_url', label: 'URL-safe' },
            { key: 'base64_raw_url', label: 'URL-safe(no padding)' },
        ],
    },
    {
        id: 'base85',
        label: 'Base85',
        variants: [{ key: 'base85_ascii85', label: 'ASCII85' }],
    },
    {
        id: 'base91',
        label: 'Base91',
        variants: [{ key: 'base91', label: 'Standard' }],
    },
];

/**
 * Maps encoding variant keys to their group and label information
 */
export const encodingVariantMap = new Map();
export const allEncodingVariants = [];
encodingGroups.forEach((group) => {
    group.variants.forEach((variant) => {
        encodingVariantMap.set(variant.key, {
            group: group.label,
            label: variant.label,
        });
        allEncodingVariants.push({ ...variant, group: group.label });
    });
});

/**
 * Hash algorithm groupings for UI organization
 */
export const hashGroups = [
    { label: 'Message Digest', keys: ['md5', 'sha1'] },
    {
        label: 'SHA-2',
        keys: ['sha224', 'sha256', 'sha384', 'sha512', 'sha512_224', 'sha512_256'],
    },
    {
        label: 'SHA-3',
        keys: ['sha3_224', 'sha3_256', 'sha3_384', 'sha3_512'],
    },
    {
        label: 'Checksums',
        keys: ['crc32_ieee', 'crc32_castagnoli', 'crc64_iso', 'crc64_ecma', 'adler32'],
    },
    {
        label: 'FNV',
        keys: ['fnv32', 'fnv32a', 'fnv64', 'fnv64a', 'fnv128', 'fnv128a'],
    },
];

/**
 * Human-readable labels for hash algorithms
 */
export const hashLabels = {
    md5: 'MD5',
    sha1: 'SHA-1',
    sha224: 'SHA-224',
    sha256: 'SHA-256',
    sha384: 'SHA-384',
    sha512: 'SHA-512',
    sha512_224: 'SHA-512/224',
    sha512_256: 'SHA-512/256',
    crc32_ieee: 'CRC32 (IEEE)',
    crc32_castagnoli: 'CRC32 (Castagnoli)',
    crc64_iso: 'CRC64 (ISO)',
    crc64_ecma: 'CRC64 (ECMA)',
    adler32: 'Adler32',
    fnv32: 'FNV-1 32',
    fnv32a: 'FNV-1a 32',
    fnv64: 'FNV-1 64',
    fnv64a: 'FNV-1a 64',
    fnv128: 'FNV-1 128',
    fnv128a: 'FNV-1a 128',
    sha3_224: 'SHA3-224',
    sha3_256: 'SHA3-256',
    sha3_384: 'SHA3-384',
    sha3_512: 'SHA3-512',
};

/**
 * Supported symmetric cipher configurations
 */
export const cryptoSuites = {
    'aes-256-gcm': { keyLen: 32, nonceLen: 12, label: 'AES-256-GCM' },
    'chacha20-poly1305': { keyLen: 32, nonceLen: 12, label: 'ChaCha20-Poly1305' },
    'xchacha20-poly1305': {
        keyLen: 32,
        nonceLen: 24,
        label: 'XChaCha20-Poly1305',
    },
};

/**
 * Coder mode descriptions for UI display
 */
export const coderModeDescriptions = {
    encode: 'Encode text or files into multiple bases.',
    decode: 'Decode text and recover raw bytes.',
    hash: 'Generate hashes for text or files.',
};

/**
 * Coder mode titles for UI display
 */
export const coderModeTitles = {
    encode: 'Encode',
    decode: 'Decode',
    hash: 'Hash',
};

/**
 * Result hints for different coder modes
 */
export const coderResultHints = {
    encode: 'Base32 / Base64 / Base85 / Base91 / Hex',
    decode: 'Decoded output',
    hash: 'MD5 / SHA / CRC / FNV',
};

/**
 * Input placeholders for different coder modes
 */
export const coderPlaceholders = {
    encode: 'Type or paste text (or pick a file below)...',
    decode: 'Paste Base32/64/85/91 text to decode...',
    hash: 'Enter text or pick a file to compute hashes',
};

/**
 * Configuration for bidirectional pair tools
 */
export const pairToolConfigs = {
    'coder-url': {
        type: 'url',
        inputLabel: 'URL Encode',
        inputHint: 'Enter original text to URL-encode.',
        inputPlaceholder: 'https://example.com/search?q=Taipei 101',
        outputLabel: 'URL Decode',
        outputHint: 'Paste encoded text to decode automatically.',
        outputPlaceholder: 'https%3A%2F%2Fexample.com%2Fsearch%3Fq%3DTaipei101',
    },
    'coder-jwt': {
        type: 'jwt',
        inputLabel: 'JWT Payload (JSON)',
        inputHint: 'Enter payload JSON; token is generated using the selected algorithm.',
        inputPlaceholder: '{\n  "sub": "1234567890",\n  "name": "John Doe"\n}',
        outputLabel: 'JWT Token',
        outputHint: 'Paste a JWT token to decode.',
        outputPlaceholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....',
    },
    'converter-html-md': {
        type: 'markdown',
        inputLabel: 'Markdown → HTML',
        inputHint: 'Enter Markdown to render HTML on the right.',
        inputPlaceholder: '# Title\n\n- item 1\n- item 2',
        outputLabel: 'HTML → Markdown',
        outputHint: 'Paste HTML to convert back to Markdown.',
        outputPlaceholder: '<h1>Title</h1>',
    },
};

/**
 * Tool group definitions for sidebar organization
 */
export const toolGroups = [
    {
        name: 'Converter',
        icon: '🔄',
        tools: [
            {
                id: 'format',
                label: 'Format Converter',
                description: 'Convert between structured data formats.',
            },
            {
                id: 'converter-image',
                label: 'Image Converter',
                description: 'JPG/PNG/WebP/AVIF with alpha preservation.',
            },
            {
                id: 'converter-html-md',
                label: 'HTML ↔ Markdown',
                description: 'Convert between Markdown and HTML.',
            },
            {
                id: 'converter-number-bases',
                label: 'Number Bases',
                description: 'Binary / Octal / Decimal / Hex conversions.',
            },
            {
                id: 'converter-units',
                label: 'Unit Converter',
                description: 'Bits, Bytes, and binary multiples.',
            },
            {
                id: 'converter-timestamp',
                label: 'Timestamp Converter',
                description: 'Convert Unix timestamps and date formats.',
            },
            {
                id: 'converter-ipv4',
                label: 'IP Tools',
                description: 'IPv4/IPv6 helpers for CIDR, ranges, and formats.',
            },
            {
                id: 'converter-diff',
                label: 'Text Diff',
                description: 'Compare texts using patience diff algorithm.',
            },
        ],
    },
    {
        name: 'Coder',
        icon: '🔐',
        tools: coderTools.map((tool) => ({
            id: tool.id,
            label: tool.label,
            description: tool.description,
        })),
    },
    {
        name: 'Generator',
        icon: '🎲',
        tools: [
            {
                id: 'generator-uuid',
                label: 'UUID',
                description: 'Generate UUID v1-v8, GUID, and ULID.',
            },
            {
                id: 'generator-useragent',
                label: 'User-Agent',
                description: 'Generate realistic browser user agents.',
            },
            {
                id: 'generator-random',
                label: 'Random',
                description: 'Random strings with customizable charset.',
            },
            {
                id: 'generator-ascii',
                label: 'ASCII Art',
                description: 'Render text into ASCII art.',
            },
            // QR generator covers OTP/WiFi/custom text flows.
            {
                id: 'generator-qr',
                label: 'QR Code',
                description: 'Generate QR codes for OTP, WiFi, or custom text.',
            },
            {
                id: 'generator-totp',
                label: 'TOTP',
                description: 'Time-based one-time passwords.',
            },
            {
                id: 'generator-sql',
                label: 'SQL Inserts',
                description: 'Generate INSERT statements from MySQL schema.',
            },
            {
                id: 'generator-ssh',
                label: 'SSH Key',
                description: 'Generate SSH public/private key pairs.',
            },
        ],
    },
    {
        name: 'Fingerprint',
        icon: '👆',
        tools: [
            {
                id: 'fingerprint-browser',
                label: 'Browser Fingerprint',
                description: 'Show readable browser/device hints.',
            },
        ],
    },
];

/**
 * Maps tool IDs to their workspace container IDs
 */
export const workspaceByTool = {
    format: 'converterWorkspace',
    'converter-image': 'imageWorkspace',
    'converter-html-md': 'pairWorkspace',
    'converter-number-bases': 'numberWorkspace',
    'converter-units': 'unitWorkspace',
    'converter-timestamp': 'timestampWorkspace',
    'converter-ipv4': 'ipv4Workspace',
    'converter-diff': 'diffWorkspace',
    'coder-encode': 'coderWorkspace',
    'coder-decode': 'coderWorkspace',
    'coder-hash': 'coderWorkspace',
    'coder-url': 'pairWorkspace',
    'coder-jwt': 'pairWorkspace',
    'coder-kdf': 'kdfWorkspace',
    'security-crypto': 'cryptoWorkspace',
    'generator-uuid': 'uuidWorkspace',
    'generator-useragent': 'userAgentWorkspace',
    'generator-random': 'randomWorkspace',
    'generator-ascii': 'asciiWorkspace',
    'generator-qr': 'qrWorkspace',
    'generator-totp': 'totpWorkspace',
    'generator-sql': 'dataWorkspace',
    'generator-ssh': 'sshWorkspace',
    'fingerprint-browser': 'fingerprintWorkspace',
    'security-ssl': 'certWorkspace',
};

/**
 * Tool category sets for type checking and filtering
 */
export const imageTools = new Set(['converter-image']);
export const coderMainTools = new Set(['coder-encode', 'coder-decode', 'coder-hash']);
export const pairTools = new Set(['converter-html-md', 'coder-url', 'coder-jwt']);
export const kdfTools = new Set(['coder-kdf']);
export const numberTools = new Set(['converter-number-bases']);
export const unitTools = new Set(['converter-units']);
export const timestampTools = new Set(['converter-timestamp']);
export const ipv4Tools = new Set(['converter-ipv4']);
export const generatorTools = new Set([
    'generator-uuid',
    'generator-useragent',
    'generator-random',
    'generator-ascii',
    'generator-qr',
    'generator-totp',
    'generator-sql',
    'generator-ssh',
]);
export const fingerprintTools = new Set(['fingerprint-browser']);
export const certTools = new Set(['security-ssl']);
export const cryptoToolSet = new Set(['security-crypto']);
export const uuidToolSet = new Set(['generator-uuid']);
export const userAgentToolSet = new Set(['generator-useragent']);
export const randomToolSet = new Set(['generator-random']);
export const totpToolSet = new Set(['generator-totp']);
export const qrToolSet = new Set(['generator-qr']);
export const dataToolSet = new Set(['generator-sql']);
export const sshToolSet = new Set(['generator-ssh']);

/**
 * Set of all implemented tool IDs
 */
export const implementedTools = new Set([
    'format',
    'converter-image',
    'converter-html-md',
    'generator-uuid',
    'generator-useragent',
    'generator-random',
    'generator-qr',
    'generator-totp',
    'generator-sql',
    'generator-ssh',
    'fingerprint-browser',
    'converter-number-bases',
    'converter-units',
    'converter-timestamp',
    'converter-ipv4',
    'converter-diff',
    'coder-encode',
    'coder-decode',
    'coder-hash',
    'coder-url',
    'coder-jwt',
    'coder-kdf',
    'security-crypto',
    'security-ssl',
]);

/**
 * Tool information mapping for quick lookups
 */
export const toolInfo = {};

/**
 * Workspace IDs for different tool categories
 */
export const workspaceIds = [
    'converterWorkspace',
    'coderWorkspace',
    'uuidWorkspace',
    'userAgentWorkspace',
    'randomWorkspace',
    'asciiWorkspace',
    'qrWorkspace',
    'totpWorkspace',
    'dataWorkspace',
    'sshWorkspace',
    'fingerprintWorkspace',
    'pairWorkspace',
    'imageWorkspace',
    'numberWorkspace',
    'unitWorkspace',
    'timestampWorkspace',
    'ipv4Workspace',
    'diffWorkspace',
    'kdfWorkspace',
    'certWorkspace',
    'cryptoWorkspace',
];

/**
 * Default decoder for coder operations
 */
export const defaultDecoder = allEncodingVariants[0]?.key || '';

/**
 * UUID display configuration
 */
export const uuidDisplayOrder = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'guid', 'ulid'];
export const uuidDisplayLabels = {
    guid: 'GUID',
    ulid: 'ULID',
};
